### ISSUE TITLE
add form validation (Backend)

### ISSUE THREAD

**Issue by ajaybor0** [ajaybor0/MERN-eCommerce#32]
Add server-side data validation using [express-validator](https://express-validator.github.io/docs)

**Comment by Tharuneshwarv** [comment]
@ajaybor0 can i work on this issue ?

**Comment by Tharuneshwarv** [comment]
@ajaybor0 do you have any api collection for testing purpose ?

**Comment by ajaybor0** [comment]
@Tharuneshwarv Yeah, I do have. Could you share your email ID?

**Comment by Tharuneshwarv** [comment]
tharuneshwarv@gmail.com

**Comment by ajaybor0** [comment]
@Tharuneshwarv I've shared api collection, please check your email.

**Comment by Tharuneshwarv** [comment]
I'll check

**Comment by Tharuneshwarv** [comment]
@ajaybor0 link has become invalid. Can you send it again ?

**Comment by ajaybor0** [comment]
@Tharuneshwarv https://restless-crater-731529.postman.co/workspace/New-Team-Workspace~df318fb8-7c6b-489e-abe8-9caaa0959e6f/collection/20364589-c4fcd31b-5302-4146-928d-8a44f043d5b3?action=share&creator=20364589

**Comment by Tharuneshwarv** [comment]
@ajaybor0 Here is the PR: https://github.com/ajaybor0/MERN-eCommerce/pull/39 . You can review it and let me know if any changes are required.

**Comment by ajaybor0** [comment]
@Tharuneshwarv 🙏 Thanks for your collaboration!
